In [173]:
import pandas as pd
import numpy as np

In [174]:
train_data = r'C:\Users\narma\Dropbox\datasets_edvancer_project\emplyee_leaving_analytics\hr_train.csv'
prediction_data = r'C:\Users\narma\Dropbox\datasets_edvancer_project\emplyee_leaving_analytics\hr_test.csv'

In [175]:
hr_df = pd.read_csv(train_data)

In [176]:
hr_df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.42,0.46,2,150,3,0,1,0,sales,medium
1,0.66,0.77,2,171,2,0,0,0,technical,medium
2,0.55,0.49,5,240,3,0,0,0,technical,high
3,0.22,0.88,4,213,3,1,0,0,technical,medium
4,0.20,0.72,6,224,4,0,1,0,technical,medium
...,...,...,...,...,...,...,...,...,...,...
10494,0.82,0.84,3,237,2,0,0,0,technical,low
10495,0.85,0.81,3,205,3,0,0,0,marketing,high
10496,0.32,0.95,5,172,2,0,1,0,sales,low
10497,0.51,0.76,4,140,3,0,1,0,support,low
10498,0.80,0.68,4,199,2,0,0,0,IT,medium

In [177]:
id_pred_df = pd.read_csv(prediction_data)

In [178]:
id_pred_df

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,sales,salary
0,0.38,0.53,2,157,3,0,0,sales,low
1,0.80,0.86,5,262,6,0,0,sales,medium
2,0.10,0.77,6,247,4,0,0,sales,low
3,0.45,0.54,2,135,3,0,0,sales,low
4,0.11,0.81,6,305,4,0,0,sales,low
...,...,...,...,...,...,...,...,...,...
4495,0.88,0.61,4,177,4,1,0,support,low
4496,0.11,0.85,7,302,4,0,0,sales,low
4497,1.00,0.88,4,191,4,0,0,technical,low
4498,0.92,0.98,3,257,3,0,1,sales,medium
4499,0.37,0.52,2,155,3,0,0,technical,medium

In [191]:
#Transform categorories into numericals

from sklearn.preprocessing import OneHotEncoder , OrdinalEncoder
from sklearn.compose import ColumnTransformer

categorical_feature = ["sales", "salary"]
one_hot = OneHotEncoder(drop='first')
oen = OrdinalEncoder()
transformer = ColumnTransformer ( transformers =  [ 
                                 ( "one_hot", one_hot ,categorical_feature)]
                                 
                                 
                        ,remainder = "passthrough")
    
transformed_x_future = transformer.fit_transform(id_pred_df)
pd.DataFrame(transformed_x_future)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
future_x_data = pd.DataFrame(scaler.fit_transform(transformed_x_future))
future_x_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.318681,0.265625,0.0,0.285047,0.125,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.780220,0.781250,0.6,0.775701,0.500,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.010989,0.640625,0.8,0.705607,0.250,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.395604,0.281250,0.0,0.182243,0.125,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.021978,0.703125,0.8,0.976636,0.250,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.868132,0.390625,0.4,0.378505,0.250,1.0,0.0
4496,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.021978,0.765625,1.0,0.962617,0.250,0.0,0.0
4497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.000000,0.812500,0.4,0.443925,0.250,0.0,0.0
4498,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.912088,0.968750,0.2,0.752336,0.125,0.0,1.0
4499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.307692,0.250000,0.0,0.275701,0.125,0.0,0.0

In [192]:

transformed_x_test = transformer.fit_transform(x_test)
pd.DataFrame(transformed_x_test)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.73,1.00,5.0,274.0,5.0,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.55,0.71,3.0,211.0,2.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.60,0.54,3.0,265.0,3.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.41,0.56,2.0,154.0,3.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.65,0.82,5.0,265.0,3.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2877,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.86,0.98,3.0,158.0,5.0,0.0,0.0
2878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.10,0.94,6.0,309.0,4.0,0.0,0.0
2879,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.43,0.82,2.0,221.0,5.0,0.0,0.0
2880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.99,0.55,3.0,197.0,2.0,0.0,0.0
2881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.52,0.91,5.0,193.0,2.0,0.0,0.0

In [144]:
future_x_data

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.318681,0.265625,0.0,0.285047,0.125,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.5,0.780220,0.781250,0.6,0.775701,0.500,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.010989,0.640625,0.8,0.705607,0.250,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.395604,0.281250,0.0,0.182243,0.125,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.021978,0.703125,0.8,0.976636,0.250,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.868132,0.390625,0.4,0.378505,0.250,1.0,0.0
4496,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.021978,0.765625,1.0,0.962617,0.250,0.0,0.0
4497,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.000000,0.812500,0.4,0.443925,0.250,0.0,0.0
4498,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.5,0.912088,0.968750,0.2,0.752336,0.125,0.0,1.0
4499,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.5,0.307692,0.250000,0.0,0.275701,0.125,0.0,0.0

In [179]:
hrcl_df = hr_df

In [180]:
# Function to detect outliers using IQR method for each column
def detect_outliers_iqr_df(hrcl_df, columns):
    outliers = {}
    for col in columns:
        q1, q3 = np.percentile(hrcl_df[col], [25, 75])
        iqr = q3 - q1
        lower_bound = q1 - (1.5 * iqr)
        upper_bound = q3 + (1.5 * iqr)
        outliers[col] = hrcl_df[(hrcl_df[col] < lower_bound) | (hrcl_df[col] > upper_bound)][col]
    return outliers

In [181]:
# Detect outliers in specified columns
columns_to_check = ['time_spend_company','average_montly_hours','number_project','satisfaction_level','last_evaluation']  # Specify the columns to check for outliers
outliers = detect_outliers_iqr_df(hrcl_df , columns_to_check)
print("Outliers:", outliers)

Outliers: {'time_spend_company': 19        6
21        6
24        6
36        8
43        6
         ..
10432     6
10480    10
10486     6
10490     6
10493     6
Name: time_spend_company, Length: 894, dtype: int64, 'average_montly_hours': Series([], Name: average_montly_hours, dtype: int64), 'number_project': Series([], Name: number_project, dtype: int64), 'satisfaction_level': Series([], Name: satisfaction_level, dtype: float64), 'last_evaluation': Series([], Name: last_evaluation, dtype: float64)}

In [182]:
# Remove outliers from specified columns
hrcl_clean = hrcl_df.copy()
for col in columns_to_check:
    hrcl_clean = hrcl_clean[~hrcl_clean[col].isin(outliers[col])]

In [183]:
hrcl_clean

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,sales,salary
0,0.42,0.46,2,150,3,0,1,0,sales,medium
1,0.66,0.77,2,171,2,0,0,0,technical,medium
2,0.55,0.49,5,240,3,0,0,0,technical,high
3,0.22,0.88,4,213,3,1,0,0,technical,medium
4,0.20,0.72,6,224,4,0,1,0,technical,medium
...,...,...,...,...,...,...,...,...,...,...
10494,0.82,0.84,3,237,2,0,0,0,technical,low
10495,0.85,0.81,3,205,3,0,0,0,marketing,high
10496,0.32,0.95,5,172,2,0,1,0,sales,low
10497,0.51,0.76,4,140,3,0,1,0,support,low
10498,0.80,0.68,4,199,2,0,0,0,IT,medium

In [184]:
y = hrcl_clean['left']
y

0        1
1        0
2        0
3        0
4        1
        ..
10494    0
10495    0
10496    1
10497    1
10498    0
Name: left, Length: 9605, dtype: int64

In [185]:
X = hrcl_clean.drop ('left',axis = 1)
X

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,sales,salary
0,0.42,0.46,2,150,3,0,0,sales,medium
1,0.66,0.77,2,171,2,0,0,technical,medium
2,0.55,0.49,5,240,3,0,0,technical,high
3,0.22,0.88,4,213,3,1,0,technical,medium
4,0.20,0.72,6,224,4,0,0,technical,medium
...,...,...,...,...,...,...,...,...,...
10494,0.82,0.84,3,237,2,0,0,technical,low
10495,0.85,0.81,3,205,3,0,0,marketing,high
10496,0.32,0.95,5,172,2,0,0,sales,low
10497,0.51,0.76,4,140,3,0,0,support,low
10498,0.80,0.68,4,199,2,0,0,IT,medium

In [186]:
from sklearn.model_selection import train_test_split

In [187]:
x_train , x_test , y_train , y_test = train_test_split ( X , y , test_size = 0.3 , random_state = 87)

In [188]:
x_train

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,sales,salary
8698,0.96,0.83,3,233,3,0,0,sales,medium
3906,0.39,0.49,2,142,3,0,0,sales,low
740,0.42,0.91,2,176,3,0,0,technical,low
2046,0.61,0.56,4,176,3,0,0,hr,medium
2013,0.82,0.90,4,232,3,0,0,RandD,low
...,...,...,...,...,...,...,...,...,...
2110,0.96,0.45,6,232,2,1,0,product_mng,low
5624,0.51,0.64,3,203,3,0,0,sales,low
5890,0.69,0.64,3,286,3,0,0,technical,medium
161,0.57,0.85,4,164,3,0,0,sales,low
9330,0.40,0.55,2,131,3,0,0,product_mng,medium

In [189]:
y_test

6008    1
4735    0
4330    0
1949    0
1309    0
       ..
8263    1
4471    1
1435    1
5355    0
3830    0
Name: left, Length: 2882, dtype: int64

In [156]:
from imblearn.over_sampling import RandomOverSampler

In [157]:
#ros = RandomOverSampler (sampling_strategy = 1)
#x_res , y_res = ros.fit_resample(x_train , y_train)

In [158]:
#y_res.value_counts()

left
0    4736
1    4736
Name: count, dtype: int64

In [193]:
transformed_x_train = transformer.fit_transform(x_train)
pd.DataFrame(transformed_x_train)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.96,0.83,3.0,233.0,3.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.39,0.49,2.0,142.0,3.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.42,0.91,2.0,176.0,3.0,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.61,0.56,4.0,176.0,3.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.82,0.90,4.0,232.0,3.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6718,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.96,0.45,6.0,232.0,2.0,1.0,0.0
6719,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.51,0.64,3.0,203.0,3.0,0.0,0.0
6720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.69,0.64,3.0,286.0,3.0,0.0,0.0
6721,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.57,0.85,4.0,164.0,3.0,0.0,0.0
6722,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.40,0.55,2.0,131.0,3.0,0.0,0.0

In [194]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
trans_res_x = pd.DataFrame(scaler.fit_transform(transformed_x_train))
trans_res_x

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.956044,0.734375,0.2,0.640187,0.333333,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.329670,0.203125,0.0,0.214953,0.333333,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.362637,0.859375,0.0,0.373832,0.333333,0.0,0.0
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.571429,0.312500,0.4,0.373832,0.333333,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.802198,0.843750,0.4,0.635514,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6718,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.956044,0.140625,0.8,0.635514,0.000000,1.0,0.0
6719,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.461538,0.437500,0.2,0.500000,0.333333,0.0,0.0
6720,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.659341,0.437500,0.2,0.887850,0.333333,0.0,0.0
6721,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.527473,0.765625,0.4,0.317757,0.333333,0.0,0.0
6722,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.340659,0.296875,0.0,0.163551,0.333333,0.0,0.0

In [195]:
y_train

8698    0
3906    1
740     0
2046    0
2013    0
       ..
2110    0
5624    1
5890    0
161     0
9330    1
Name: left, Length: 6723, dtype: int64

In [161]:
x_test

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,promotion_last_5years,sales,salary
6008,0.73,1.00,5,274,5,0,0,product_mng,low
4735,0.55,0.71,3,211,2,0,0,management,low
4330,0.60,0.54,3,265,3,1,0,sales,medium
1949,0.41,0.56,2,154,3,0,1,support,medium
1309,0.65,0.82,5,265,3,0,0,IT,low
...,...,...,...,...,...,...,...,...,...
8263,0.86,0.98,3,158,5,0,0,sales,low
4471,0.10,0.94,6,309,4,0,0,technical,medium
1435,0.43,0.82,2,221,5,0,0,sales,medium
5355,0.99,0.55,3,197,2,0,0,IT,medium
3830,0.52,0.91,5,193,2,0,0,support,low

In [208]:
#Transform categorories into numericals
    
transformed_x_test = transformer.fit_transform(x_test)
pd.DataFrame(transformed_x_test)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x_test_trans = pd.DataFrame(scaler.fit_transform(transformed_x_test))
x_test_trans

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.703297,1.000000,0.6,0.830986,1.000000,0.0,0.0
1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.505495,0.546875,0.2,0.535211,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.560440,0.281250,0.2,0.788732,0.333333,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.351648,0.312500,0.0,0.267606,0.333333,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.615385,0.718750,0.6,0.788732,0.333333,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2877,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.846154,0.968750,0.2,0.286385,1.000000,0.0,0.0
2878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.010989,0.906250,0.8,0.995305,0.666667,0.0,0.0
2879,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.373626,0.718750,0.0,0.582160,1.000000,0.0,0.0
2880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.989011,0.296875,0.2,0.469484,0.000000,0.0,0.0
2881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.472527,0.859375,0.6,0.450704,0.000000,0.0,0.0

In [196]:
from sklearn.ensemble import RandomForestClassifier

In [197]:
from sklearn.model_selection import RandomizedSearchCV

In [198]:
clf = RandomForestClassifier()

In [199]:
param_dist = {'class_weight':['balanced'], 
        'criterion':['gini'],
        'max_depth':[None,5,6,9,10,12],
        'min_samples_split':[20,25,30,35,40,45,50,55,70],
        'min_samples_leaf':[5,10,15,20,30,35,40,], # Till here, its same as DT
              
        "n_estimators":[200,300,500], # Number of trees to build
        "max_features": [6,7,9,12,15,17],
          "max_samples": [None, 0.7, 0.8]
         }

In [204]:
random_search = RandomizedSearchCV(clf, param_distributions=param_dist,
                                   n_iter=20,
                                   scoring='roc_auc',
                                   cv=5,
                                   n_jobs=-1, 
                                   verbose=20, 
                                   random_state = 7).fit(trans_res_x , y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

In [ ]:
random_search.best_estimator_

In [ ]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        # np.flatnonzero(): Return the indices of the non-zero elements
        
        for candidate in candidates:
            print(f"Model with rank: {i}")
            print(f"Mean validation score: {round(results['mean_test_score'][candidate], 5)} \
                  std: {round(results['std_test_score'][candidate], 5)}")
            print(f"Parameters: {results['params'][candidate]}")
            print("")

In [ ]:
random_search.best_estimator_

In [87]:
report(random_search.cv_results_, 3)

Model with rank: 1
Mean validation score: 0.91907                   std: 0.01275
Parameters: {'n_estimators': 200, 'min_samples_split': 45, 'min_samples_leaf': 10, 'max_samples': None, 'max_features': 9, 'max_depth': None, 'criterion': 'gini', 'class_weight': 'balanced'}

Model with rank: 2
Mean validation score: 0.9057                   std: 0.0113
Parameters: {'n_estimators': 300, 'min_samples_split': 55, 'min_samples_leaf': 10, 'max_samples': 0.7, 'max_features': 9, 'max_depth': None, 'criterion': 'gini', 'class_weight': 'balanced'}

Model with rank: 3
Mean validation score: 0.89909                   std: 0.01117
Parameters: {'n_estimators': 300, 'min_samples_split': 55, 'min_samples_leaf': 20, 'max_samples': None, 'max_features': 15, 'max_depth': 12, 'criterion': 'gini', 'class_weight': 'balanced'}

In [205]:
rf = RandomForestClassifier(**{'n_estimators': 200, 'min_samples_split': 45, 'min_samples_leaf': 10, 'max_samples': None, 'max_features': 9, 
                               'max_depth': None, 'criterion': 'gini', 'class_weight': 'balanced'}).fit(trans_res_x,y_train)

In [206]:
from sklearn.metrics import roc_curve , precision_recall_curve , roc_auc_score

In [211]:
y_test_predict = rf.predict_proba(x_test_trans)[:,1]
auc_sc_t = roc_auc_score(y_test , y_test_predict)
auc_sc_t

0.837500398862217

In [212]:
future_train_df = rf.predict(future_x_data)

In [213]:
future_train_df

array([1, 0, 1, ..., 0, 0, 1], dtype=int64)

In [214]:
result_file = pd.DataFrame(future_train_df)

In [215]:
result_file

      0
0     1
1     0
2     1
3     1
4     1
...  ..
4495  0
4496  1
4497  0
4498  0
4499  1

[4500 rows x 1 columns]

In [220]:
result_file.to_csv(r'C:\Users\narma\Dropbox\datasets_edvancer_project\emplyee_leaving_analytics\result\Narmathaa_Palanisamy_Part4_08.csv')

KeyError: '0'